{{ config(materialized='table') }}

SELECT 
    f.STORE_ID,
    f.DEPT_ID,
    COUNT(DISTINCT f.STORE_DATE)    AS WEEKS_OF_DATA,
    AVG(f.STORE_WEEKLY_SALES)       AS AVG_WEEKLY_SALES,
    SUM(f.STORE_WEEKLY_SALES)       AS TOTAL_SALES,
    MAX(f.STORE_WEEKLY_SALES)       AS MAX_WEEKLY_SALES,
    MIN(f.STORE_WEEKLY_SALES)       AS MIN_WEEKLY_SALES,
    CURRENT_TIMESTAMP()             AS INSERT_DATE,
    CURRENT_TIMESTAMP()             AS UPDATE_DATE

FROM {{ ref('walmart_fact_table') }} f 

WHERE f.VRSN_END_DATE IS NULL 

GROUP BY f.STORE_ID, f.DEPT_ID
ORDER BY TOTAL_SALES DESC